name: learn-github-actions
on:
  push:
    branches:
      - 'master'
    paths:
      - '*.md'
jobs:
  produce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat README.md | wc -w >> wordcount
      - uses: actions/upload-artifact@v2
        with:
          name: wc-file
          path: ./wordcount

  consume:
    needs: produce
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wc-file
      - run: |
          WORDS=$(cat wordcount)
          echo "Wordcount $WORDS"
