name: learn-github-actions
on: push
  branches: master
  paths:
    - *.md
jobs:
  produce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat README.md | wc -w >> wordcount

  consume:
    needs: produce
    steps:
      - run: WORDS="$(cat wordcount)"
      - run: echo "Wordcount $WORDS"
